version: '3'
services:
    web:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/code
        depends_on:
            - db
    db:
        image: mongo:4.4
        hostname: test_mongodb
        ports:
          - 27017:27017